/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Audio: typeof import('./src/steps/audio.vue')['default']
    Cover: typeof import('./src/steps/cover.vue')['default']
    Embed: typeof import('./src/steps/embed.vue')['default']
    Info: typeof import('./src/steps/info.vue')['default']
    Lyrics: typeof import('./src/steps/lyrics.vue')['default']
  }
}
